version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "0.0.0.0:8000:8000"
    command: python mange.py runserver 0.0.0.0:8000

volumes:
  static-date: